# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #16130b
foreground            #e9e2d4

cursor                #e1c46d
cursor_text_color     #3c2f00

selection_background  #50462a
selection_foreground  #f1e1bb

url_color             #accfaf

# Black
color0   #231f17
color8   #2d2a21

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #accfaf
color10  #2e4e35

# Yellow
color3   #d4c5a1
color11  #50462a

# Blue
color4   #e1c46d
color12  #564500

# Magenta
color5   #c7ecca
color13  #c7ecca

# Cyan
color6   #715c0c
color14  #fee086

# White
color7   #cec6b4
color15  #e9e2d4

# Tabs
active_tab_background   #564500
active_tab_foreground   #fee086
inactive_tab_background #231f17
inactive_tab_foreground #cec6b4
tab_bar_background      #16130b
