# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #1a1110
foreground            #f1dfdb

cursor                #ffb4a7
cursor_text_color     #561e15

selection_background  #5d3f3a
selection_foreground  #ffdad4

url_color             #ddc48c

# Black
color0   #271d1c
color8   #322826

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #ddc48c
color10  #564519

# Yellow
color3   #e7bdb5
color11  #5d3f3a

# Blue
color4   #ffb4a7
color12  #733429

# Magenta
color5   #fae0a6
color13  #fae0a6

# Cyan
color6   #904b3f
color14  #ffdad4

# White
color7   #d8c2be
color15  #f1dfdb

# Tabs
active_tab_background   #733429
active_tab_foreground   #ffdad4
inactive_tab_background #271d1c
inactive_tab_foreground #d8c2be
tab_bar_background      #1a1110
