# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #181115
foreground            #eddfe4

cursor                #f8b1dd
cursor_text_color     #4f1e42

selection_background  #57404e
selection_foreground  #fadaeb

url_color             #f4b9a0

# Black
color0   #251e21
color8   #2f282c

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #f4b9a0
color10  #653c29

# Yellow
color3   #ddbecf
color11  #57404e

# Blue
color4   #f8b1dd
color12  #693459

# Magenta
color5   #ffdbcc
color13  #ffdbcc

# Cyan
color6   #844c72
color14  #ffd8ee

# White
color7   #d3c2ca
color15  #eddfe4

# Tabs
active_tab_background   #693459
active_tab_foreground   #ffd8ee
inactive_tab_background #251e21
inactive_tab_foreground #d3c2ca
tab_bar_background      #181115
