#######################
#######################
# OLYMPUS HYPRIDLE.CONF
# V1.0 - STABLE
# GIT: jjjjppppllll
#######################
#######################

# THIS ALLOWS PROPER LID MANAGEMENT ON A LAPTOP
# BUT ALSO SETS HYPRIDLE

general {
    lock_cmd = pidof hyprlock || hyprlock     
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on 
}
listener {
    timeout = 300                             
    on-timeout = loginctl lock-session          
}

listener {
    timeout = 330                               
    on-timeout = hyprctl dispatch dpms off  
    on-resume = hyprctl dispatch dpms on     
}
