# Généré par matugen — ne pas éditer manuellement
$background = rgb({{colors.background.default.hex}})
$foreground = rgb({{colors.on_background.default.hex}})
$primary    = rgb({{colors.primary.default.hex}})
$on_primary = rgb({{colors.on_primary.default.hex}})
$secondary  = rgb({{colors.secondary.default.hex}})
$tertiary   = rgb({{colors.tertiary.default.hex}})
$surface    = rgb({{colors.surface.default.hex}})
$on_surface = rgb({{colors.on_surface.default.hex}})
$error      = rgb({{colors.error.default.hex}})